---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@74f3dc641cd75d4ac5be3c1eecf04ba094eb9276 # main
    name: GitHub Release
