---
name: Workflow Validation
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"

permissions:
  contents: read

jobs:
  validate-workflows:
    uses: appvia/appvia-cicd-workflows/.github/workflows/github-workflow-validation.yml@641e8b22034b8eb49e2bbc11ef103d1324eb93e2 # main
    name: Validate GitHub Workflows
